#!/bin/bash

gamemode_ini="${HOME}/.config/gamemode.ini"

mkdir -p "$(dirname "$gamemode_ini")"
cat > "$gamemode_ini" <<-EOF
	[custom]
	start = ${DOTFILE_DIR}/bin/gui/mouseaccel off
	end   = ${DOTFILE_DIR}/bin/gui/mouseaccel on
EOF
