#!/bin/bash

script_path=$(readlink -f "$0")
script_dir=$(dirname "$script_path")

source "${script_dir}/../sync/lib.sh"

steam_flatpak='com.valvesoftware.Steam'

function steam-flatpak-is-installed() {
  flatpak run --command=true "$steam_flatpak"
}

if ! steam-flatpak-is-installed; then
  printf 'Steam Flatpak is not installed; skipping\n' >&2
  exit 0
fi

if ! [[ -d "$SYNC_ROOT_DIR" ]]; then
  printf 'sync directory "%s" is not present; skipping\n' >&2
  exit 0
fi

# This is the default set of directories in the Steam Flatpak PATH.
default_path='/app/bin:/app/utils/bin:/usr/bin'
gaming_steam_dir="${DOTFILE_DIR}/bin/gaming/steam"
gamescope_flatpak_bin_dir='/usr/lib/extensions/vulkan/gamescope/bin'

# ENABLE_GAMESCOPE_WSI=0 will disable HDR, but fixes the Steam overlay
# being broken in Gamescope.
#
# See:
# https://github.com/ValveSoftware/gamescope/issues/835#issuecomment-2361846080
# https://github.com/ValveSoftware/gamescope/issues/1225
flatpak override --user 'com.valvesoftware.Steam' \
  --filesystem="${SYNC_ROOT_DIR}/game-saves" \
  --filesystem="${gaming_steam_dir}" \
  --env='SDL_VIDEODRIVER=x11' \
  --env="PATH=${gaming_steam_dir}:${default_path}:${gamescope_flatpak_bin_dir}" \
  --env='ENABLE_GAMESCOPE_WSI=0'
