VIM_DIR="$HOME/.vim"
VIM_BUNDLE_DIR="$HOME/.vim/bundle"
VIM_RUNTIME_DIR="$DOTFILE_DIR/vim/config"
PYTHON_DEV_VENV="$HOME/.cache/python-venvs/neovim-dev"

export VIM_BUNDLE_DIR VIM_DIR VIM_RUNTIME_DIR PYTHON_DEV_VENV
