#!/bin/bash

delete_flags=()
branches=()

while [[ "$#" -gt 0 ]]; do
    if [[ "$1" == '-f' || "$1" == '--force' ]]; then
        delete_flags=('--force')
        shift
        continue
    fi
    branches=("${branches[@]}" "$1")
    shift
done

for b in "${branches[@]}"; do
    git branch --delete "${delete_flags[@]}" "$b"
    if git rev-parse --verify "origin/${b}" >/dev/null 2>&1; then
        git push origin --delete "${delete_flags[@]}" "$b"
    fi
done
