#!/bin/zsh -l

function venv_site_packages() {
    local venv=$1

    find "$venv" -name site-packages -type d | head -n1
}

python_project_root=$(dirname "$(search-upwards-for-one-of pyproject.toml Pipfile requirements.txt)")
if [[ -n "$python_project_root" ]]; then
    cd "$python_project_root"
    python_local_venv="$PWD/.venv"
    if [[ -d "$python_local_venv" ]]; then
        PYTHONPATH=$(pathvarmunge "$PYTHONPATH" "$(venv_site_packages "$python_local_venv")")
    elif [[ -f 'pyproject.toml' ]]; then
        poetry_venv=$(poetry env info -p 2>/dev/null)
        if [[ -n "$poetry_venv" ]]; then
            PYTHONPATH=$(pathvarmunge "$PYTHONPATH" "$(venv_site_packages "$poetry_venv")")
        fi
    elif [[ -f 'Pipfile' ]]; then
        pipenv_venv=$(pipenv --venv 2>/dev/null)
        if [[ -n "$pipenv_venv" ]]; then
            PYTHONPATH=$(pathvarmunge "$PYTHONPATH" "$(venv_site_packages "$pipenv_venv")")
        fi
    fi
fi

export PYTHONPATH
exec "$PYTHON_DEV_VENV/bin/jedi-language-server"
