#!/bin/zsh

wm=$1

cat <<EOF
exec_always --no-startup-id \$DOTFILE_DIR/bin/i3/desktop-daemons "$wm"
exec_always --no-startup-id \$DOTFILE_DIR/bin/i3/persistent-services
EOF

if [[ "$wm" == 'i3' ]]; then
    cat <<'EOF'
exec_always --no-startup-id $DOTFILE_DIR/bin/x11/orient-displays
exec_always --no-startup-id $DOTFILE_DIR/bin/x11/configure-screensaver
EOF
fi
