#!/bin/zsh

if [[ -n "$DISPLAYNAME_PRIMARY" ]]; then
    cat <<EOF
    workspace "game"    output $DISPLAYNAME_PRIMARY
EOF
fi
if [[ -n "$DISPLAYNAME_SECONDARY" ]]; then
    cat <<EOF
    workspace "chat"    output $DISPLAYNAME_SECONDARY
EOF
fi
if [[ -n "$DISPLAYNAME_TERTIARY" ]]; then
    cat <<EOF
    workspace "spotify" output $DISPLAYNAME_TERTIARY
    workspace "steam"   output $DISPLAYNAME_TERTIARY
EOF
fi
