#!/bin/zsh

game_workspace='game'

# Games identified by instance (the first field of WM_CLASS).
declare -a game_instances
game_instances=(
    '^darksoulsremastered.exe$'
    '^eso64.exe$'
    '^Faeria.x86_64$'
    '^grim dawn.exe$'
    '^hl2_linux$'
    '^payday2_release$'
    '^portal2_linux$'
    '^sc2_x64.exe$'
    '^SOR4$'
    '^UnderMine$'
    '^valheim.x86_64$'
    '^wow.exe$'
)

# Games identified by class (second field of WM_CLASS).
declare -a game_classes
game_classes=(
    '^Hellpoint'
    '^Minecraft'
    'Slay the Spire$'
    '^Terraria.bin.x86_64$'

    # Covers Steam applications running in a Wine virtual desktop.
    '^steam_app_[0-9]+$'
)

# Games identified by window title (_NET_WM_NAME, or WM_NAME as a fallback).
declare -a game_titles
game_titles=(
    '^Binding of Isaac'
    '^Chronicon$'
    '^Factorio'
    '^Heroes of Hammerwatch'
)


function window_rule() {
    # The attribute by which the window is selected,
    # e.g. "instance", "class", or "title".
    local selector=$1
    shift

    echo -n "for_window [$selector=\""
    while [[ -n "$1" ]]; do
        echo -n "$1"
        if [[ -n "$2" ]]; then
            echo -n '|'
        fi
        shift
    done
    echo -n '"] '
    echo -n "move container to workspace $game_workspace, fullscreen enable, workspace $game_workspace"
    echo
}

window_rule instance "${game_instances[@]}"
window_rule class    "${game_classes[@]}"
window_rule title    "${game_titles[@]}"
