#!/bin/zsh

wm=$1

source "$DOTFILE_DIR/theme/$DESKTOP_THEME/colors"

cat <<EOF
set \$bg_shade0 $NORD_POLARNIGHT_0
set \$bg_shade1 $NORD_POLARNIGHT_1
set \$bg_shade2 $NORD_POLARNIGHT_2
set \$bg_shade3 $NORD_POLARNIGHT_3

set \$fg_shade0 $NORD_SNOWSTORM_0
set \$fg_shade1 $NORD_SNOWSTORM_1
set \$fg_shade2 $NORD_SNOWSTORM_2
set \$fg_shade3 $NORD_SNOWSTORM_2

set \$yellow    $NORD_AURORA_YELLOW
set \$green     $NORD_AURORA_GREEN
set \$orange    $NORD_AURORA_ORANGE
set \$red       $NORD_AURORA_RED
set \$blue      $NORD_FROST_DARK_BLUJE
set \$cyan      $NORD_FROST_CYAN

EOF

cat <<'EOF'
# To make a solid, single color border, make sure border, background, indicator, and
# child_border all have the same value.
#
# <colorclass>          <border>    <background> <text>      <indicator>  <child_border>
client.focused          $fg_shade1  $fg_shade1   $fg_shade3  $fg_shade1   $fg_shade1
client.focused_inactive $bg_shade1  $bg_shade1   $fg_shade0  $bg_shade1   $bg_shade1
client.unfocused        $bg_shade1  $bg_shade1   $fg_shade0  $bg_shade1   $bg_shade1
client.urgent           $bg_shade1  $red         $fg_shade3  $bg_shade3   $red
EOF
