#!/bin/zsh

wm=$1

# Theming options that must be set dynamically, based on
# the current display profile ("HD" or "UHD").
display_profile=$("$DOTFILE_DIR/bin/gui/display-profile")

# DPI scaling is turned on for i3 but off for sway.
# Don't use larger gaps, border sizes unless we're running sway.
if [[ "$display_profile" == 'UHD' && "$wm" == 'sway' ]]; then
    border_sz=4
    gaps_sz=4
    cursor_sz=64
    font_sz=22
else
    border_sz=2
    gaps_sz=2
    cursor_sz=32
    font_sz=16
fi

cat <<EOF
default_border pixel $border_sz
default_floating_border pixel $border_sz

# This sets the default gap size for new workspaces.
gaps outer $gaps_sz
gaps inner $gaps_sz

font pango:mononoki Nerd Font Mono $font_sz

# See: https://wiki.archlinux.org/title/Cursor_themes#GNOME
#
# This is required for GTK applications to display the correct cursor.
#
# FIXME: Setting the cursor-theme to Bluecurve doesn't seem to do anything.
exec_always --no-startup-id gsettings set org.gnome.desktop.interface cursor-size "$cursor_sz"
exec_always --no-startup-id gsettings set org.gnome.desktop.interface cursor-theme Bluecurve

exec_always --no-startup-id \$DOTFILE_DIR/bin/x11/xresources
exec_always --no-startup-id \$DOTFILE_DIR/bin/i3/setbg
EOF

if [[ "$wm" == 'sway' ]]; then
    # Setting xcursor_theme at runtime does not work unless displays are
    # turned off and then back on again, for some reason. So we need
    # to make sure this bit is persisted in the config file.
    echo seat seat0 xcursor_theme Bluecurve $cursor_sz
fi
