#!/usr/bin/env bash

set -e

CONFIG="install.conf"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

# When installing on a new fresh system, we need to ensure that
# $DOTFILE_DIR and $last_dotfile_install_path are set -- so we
# explicitly source the environment here.
source "${BASEDIR}/shell/shenv"

if [[ ! "$DISPLAY" =~ ^: ]]; then
    # Configuring X11 junk isn't appropriate when the display
    # isn't local, so skip it in that case.
    unset DISPLAY
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
rc="$?"
# Only update the install last-run timestamp if dotfile installation succeeds.
# This way, the user will continue to get warnings about needing to run the
# install script if dotfile installation fails.
if [[ "$rc" == 0 ]]; then
    date +%s > "$_last_dotfile_install_path" 2>&1
fi
exit "$rc"
