#!/usr/bin/env bash

set -e

CONFIG="install.conf"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

# Some install scripts depend on DOTFILE_DIR being set, which will not be the
# case in brand new environments.
export DOTFILE_DIR="$HOME/.dotfiles"

if [[ ! "$DISPLAY" =~ ^: ]]; then
    # Configuring X11 junk isn't appropriate when the display
    # isn't local, so skip it in that case.
    unset DISPLAY
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
rc="$?"
# Only update the install last-run timestamp if dotfile installation succeeds.
# This way, the user will continue to get warnings about needing to run the
# install script if dotfile installation fails.
if [[ "$rc" == 0 ]]; then
    # When installing on a new fresh system, we need to ensure that
    # $last_dotfile_install_path is set -- so we explicitly source
    # the environment here.
    source "${DOTFILE_DIR}/shell/shenv"

    date +%s > "$_last_dotfile_install_path" 2>&1
fi
exit "$rc"
