#!/bin/bash

if [[ -z "$DISPLAY" ]]; then
    # TODO: Determine the best way to determine the GPU vendor
    # outside an X11 environment.
    exit 0
fi

# glx_vendor_string values:
# * 'NVIDIA Corporation' for nvidia GPUs using proprietary drivers
# * 'SGI' for open source mesa drivers
glx_vendor_string=$(glxinfo | awk -F': ' '$1 == "server glx vendor string" { print $2 }')

if [[ "$glx_vendor_string" == 'NVIDIA Corporation' ]]; then
    xrender_sync_fence='true'
    vsync='opengl-swc'
elif [[ "$glx_vendor_string" == 'SGI' ]]; then
    xrender_sync_fence='false'
    vsync='opengl-mswc'
else
    echo "Unknown glx vendor string: $glx_vendor_string" >&2
    exit 1
fi

cat > "$HOME/.config/compton.conf" <<EOF
backend = "glx";
vsync = "$vsync";

glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = $xrender_sync_fence;

paint-on-overlay = false;
force-win-blend = true;

blur-background = false;

blur-background-exclude = [
    # Needed to prevent \`maim -s\` from making the entire desktop blurry.
    # This rule doesn't do anything now, but we leave it here in case we want
    # to mess with blurriness again.
    "class_g = 'slop'",
    "!(class_g = 'URxvt' || class_g = 'Rofi' || class_g = 'Polybar')",
]
blur-background-fixed = true;
use-ewmh-active-win = true;
inactive-opacity = 1;
active-opacity = 1;
mark-ovredir-focused = true;

opacity-rule = [
    "95:class_g = 'URxvt'",
    "95:class_g = 'Polybar'",
    "95:class_g = 'Rofi'",
];

focus-exclude = [
    "window_type *= 'menu'",
    "window_type = 'tooltip'",
    "window_type = 'dialog'",
    "window_type = 'toolbar'",
    "window_type = 'utility'",
    "class_g = 'vlc'",
    "class_g = 'Rofi'",

    # disable opacity, dimming for fullscreen windows
    "_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_FULLSCREEN'",
    "_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_FULLSCREEN'",
    "_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_FULLSCREEN'",
    "_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_FULLSCREEN'",
    "_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_FULLSCREEN'",
];
EOF
