#!/bin/zsh -l

pkill polybar
pkill compton
pkill dunst
pkill mmpd
pkill xautolock
pkill -f "unclutter --display $DISPLAY"

if [[ -n "$DISPLAYNAME_LEFT" ]]; then
    polybar --config="$DOTFILE_DIR/polybar/config" left &
fi
if [[ -n "$DISPLAYNAME_CENTER" ]]; then
    polybar --config="$DOTFILE_DIR/polybar/config" center &
fi
if [[ -n "$DISPLAYNAME_RIGHT" ]]; then
    polybar --config="$DOTFILE_DIR/polybar/config" right &
fi
compton --config "$DOTFILE_DIR/compton/compton.conf" &
"$DOTFILE_DIR/dunst/gen-dunst-icons.sh"
dunst -icon_path "$HOME/.cache/dunsticons" &
"$DOTFILE_DIR/bin/i3/mmpd" &
xautolock -time "$SCREENLOCK_TIME_MINUTES" -locker "$DOTFILE_DIR/bin/lockscreen" &
unclutter --display "$DISPLAY" --timeout 1 &
disown
