#!/bin/zsh -l

pkill polybar
pkill compton
pkill dunst
pkill mmpd
pkill xss-lock
pkill -f "unclutter --display $DISPLAY"

if [[ -n "$DISPLAYNAME_LEFT" ]]; then
    polybar --config="$DOTFILE_DIR/polybar/config" left &
fi
if [[ -n "$DISPLAYNAME_CENTER" ]]; then
    polybar --config="$DOTFILE_DIR/polybar/config" center &
fi
if [[ -n "$DISPLAYNAME_RIGHT" ]]; then
    polybar --config="$DOTFILE_DIR/polybar/config" right &
fi

"$DOTFILE_DIR/bin/x11/orient-displays"

compton --config "$HOME/.config/compton.conf" &
dunst -icon_path "$HOME/.cache/dunsticons" &
"$DOTFILE_DIR/bin/i3/mmpd" &
xss-lock "$DOTFILE_DIR/bin/lockscreen" &
unclutter --display "$DISPLAY" --timeout "$CURSOR_HIDE_TIME_SECONDS" &
disown
