#!/bin/bash

# TODO: Remove playerctl-git and use playerctl once the official package is updated.
pacman -S dunst rofi polybar i3-gaps i3lock maim mesa-demos noto-fonts-emoji noto-fonts-cjk ttf-font-awesome adobe-source-code-pro-fonts xautolock xcursor-bluecurve unclutter ttf-dejavu
yay -S xinit-xsession ttf-material-icons playerctl-git
