#!/bin/bash

wm=$1

if [[ "$wm" != 'sway' ]]; then
    exit 0
fi

cat <<'EOF'
output DP-1 pos 0 0 res 3840x2160
output DP-2 pos 3840 0 res 3840x2160
output DP-3 pos 7680 0 res 3840x2160

output DP-1 adaptive_sync on
output DP-2 adaptive_sync on
output DP-3 adaptive_sync on
EOF
