#!/bin/bash

# The path to the configuration of an application to configure
# syncing for.
application=$1

set -e

if [[ -z "$application" ]]; then
	printf '%s: You must specify the path to the application to configure syncing for\n' "$0" >&2
	exit 1
fi

if ! [[ -f "$application" ]]; then
	printf "%s: no such configuration: %s\n" "$0" "$application" >&2
	exit 2
fi

script_dir=$(dirname "$(readlink -f "$0")")

source "${script_dir}/lib.sh"
source "$application"

if type postsetup &>/dev/null; then
	postsetup
fi
