#!/bin/bash

source "$DOTFILE_DIR/colors/solarized-dark"

proc_name="$1"
proc_running="$2"
proc_running_color="$3"
proc_stopped="$4"
proc_stopped_color="$5"

proc_running_color="$(eval "echo $proc_running_color")"
proc_stopped_color="$(eval "echo $proc_stopped_color")"
if pgrep -x "$proc_name" >/dev/null 2>&1; then
    echo -n "%{F$proc_running_color}$proc_running"
else
    echo -n "%{F$proc_stopped_color}$proc_stopped"
fi
