source "$ZSH_LIB_DIR/path.zsh"

for f in "$DOTFILE_DIR"/zsh/config/profile/*.zsh; do
    source "$f"
done

local_profile="$HOME/.zprofile.local"
if [[ -f "$local_profile" ]]; then
    source "$local_profile"
fi
