# Don't source system-wide rc files.
#
# My dotfiles do a lot, and these sometimes just screw things up.
#
# I'd rather integrate machine-specific stuff into my dotfiles
# as I need it.
unsetopt GLOBAL_RCS

export DOTFILE_DIR="$HOME/.dotfiles"
export ZSH_LIB_DIR="$DOTFILE_DIR/zsh/lib"
export NOTES_DIR="$HOME/sync/notes"
_last_dotfile_install_path="$HOME/.cache/last-dotfile-install"

c_search_directories=("$HOME/projects" "$HOME/src")

local_env="$HOME/.zshenv.local"
if [[ -f "$local_env" ]]; then
    source "$local_env"
fi

secret_env="$HOME/.zshenv.secret"
if [[ -f "$secret_env" ]]; then
    source "$secret_env"
fi
