#!/usr/bin/env zsh

REALHOME="$HOME"
if [[ -n "$SUDO_USER" ]]; then
    export REALHOME="$(getent passwd "$SUDO_USER" | awk -F: '{ print $6 }')"
fi
DOTFILE_DIR="$REALHOME/.dotfiles"
ZSH="$DOTFILE_DIR/zsh/oh-my-zsh"
ZSH_CUSTOM="$DOTFILE_DIR/zsh/custom"
DISABLE_AUTO_UPDATE='true'
export DOTFILE_DIR DISABLE_AUTO_UPDATE ZSH ZSH_CUSTOM

[[ -f "$REALHOME/.zshenv.local" ]] && source "$REALHOME/.zshenv.local"
