export DOTFILE_DIR="$HOME/.dotfiles"

for f in "$DOTFILE_DIR"/zsh/config/env/*.zsh; do
    source "$f"
done

local_env="$HOME/.zshenv.local"
if [[ -f "$local_env" ]]; then
    source "$local_env"
fi

secret_env="$HOME/.zshenv.secret"
if [[ -f "$secret_env" ]]; then
    source "$secret_env"
fi
