for f in "$DOTFILE_DIR"/zsh/config/rc/*.zsh; do
    source "$f"
done

_zshrc_local="$HOME/.zshrc.local"
if [[ -f "$_zshrc_local" ]]; then
    source "$_zshrc_local"
fi
unset _zshrc_local

# Clear status code from anything else that may have executed previously
return 0
