#!/usr/bin/env zsh

[[ -f "$REALHOME/.zshrc.local.pre" ]] && source "$REALHOME/.zshrc.local.pre"

source $ZSH/oh-my-zsh.sh

[[ -f "$REALHOME/.zshrc.local.post" ]] && source "$REALHOME/.zshrc.local.post"

# Clear status code from anything else that may have executed previously
return 0
